.TH HEVI 5 2024-05-12 "hevi 1.0.0-dev"
.SH NAME
hevi configuration file

.SH SYNOPSIS
.I ~/.config/hevi/config.json

.SH DESCRIPTION
This page explains how the configuration file is structured and what its fields are. 

The configuration file is a JSON file.

These are the fields of the configuration file:
.in +4
.nf
color: \fItrue\fR|\fIfalse\fR
uppercase: \fItrue\fR|\fIfalse\fR
show_size: \fItrue\fR|\fIfalse\fR
show_offset: \fItrue\fR|\fIfalse\fR
show_ascii: \fItrue\fR|\fIfalse\fR
skip_lines: \fItrue\fR|\fIfalse\fR
raw: \fItrue\fR|\fIfalse\fR
parser: "\fIspecific parser\fR"
palette: {\fIpalettes\fR}
.fi
.in

\fBNote\fR: for the \fIpalette\fR field you must specify all palettes!

You can also not put all the fields in the file, default values will be chosen.

The config file is located at:
.in +4
.nf
\fBLinux\fR, \fBMacOS\fR, \fBFreeBSD\fR, \fBOpenBSD\fR, \fBNetBSD\fR --> \fI$XDG_CONFIG_HOME/hevi/config.json\fR or if the env doesn't exist \fI$HOME/.config/hevi/config.json\fR
\fBWindows\fR --> \fI%APPDATA%/hevi/config.json\fR
\fBOther\fR --> Not supported. No config file will be read.
.in

.SH EXAMPLES
.in +4
.EX
{
	"color": true,
	"skip_lines": false,
	"parser": "data",
	"palette": {
		"normal": { "base": "yellow", "dim": false },
		"normal_alt": { "base": "yellow", "dim": true },
		"c1": { "base": "red", "dim": false },
		"c1_alt": { "base": "red", "dim": true },
		"c2": { "base": "green", "dim": false },
		"c2_alt": { "base": "green", "dim": true },
		"c3": { "base": "blue", "dim": false },
		"c3_alt": { "base": "blue", "dim": true },
		"c4": { "base": "magenta", "dim": false },
		"c4_alt": { "base": "magenta", "dim": true },
		"c5": { "base": "cyan", "dim": false },
		"c5_alt": { "base": "cyan", "dim": true }
	}
}
.EE
.in

.SH NOTES
hevi has a precedence for configuration and is:
.nf
1. Flags
2. Environment variables
3. Config file
4. Defaults
.in

.SH SEE ALSO
.BR hevi (1)
